name: "Danger JS"
on: [pull_request]

jobs: 

  name: Danger JS
  runs-on: ubuntu-latest
  steps: 
    - 
      uses: actions/checkout@v1
    - 
      name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'
        cache: 'yarn'
    - 
      name: Install project dependencies
      run: yarn --prefer-offline
    - 
      name: Danger
      uses: danger/danger-js@9.1.6
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
