name: "Danger JS"
on: [pull_request]

jobs: 
  GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
  build: ~
  env: ~
  name: "Danger JS"
  runs-on: ubuntu-latest
  steps: 
    - 
      uses: actions/checkout@v1
    - 
      name: Danger
  uses: danger/danger-js@9.1.6
  